export const SET_USER = 'SET_USER'
export const LOGOUT = 'LOGOUT'
export const POSTCARD = 'POSTCARD'
export const GETCARD = 'GETCARD'
export const GET_USER = 'GET_USER'
export const SET_CARD = 'SET_CARD' 
export const FIND_CARD = 'FIND_CARD'  
export const SET_TOTAL = 'SET_TOTAL'  